# See https://github.com/google/mono_repo.dart for details on this file
sdk:
- 2.16.1
- dev

stages:
- analyzer_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
- unit_test:
  - test:
